/*
 * This file is generated by jOOQ.
 */
package by.gsu.jooq;


import by.gsu.jooq.tables.Product;
import by.gsu.jooq.tables.SqliteSequence;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Product</code>.
     */
    public static final Product PRODUCT = by.gsu.jooq.tables.Product.PRODUCT;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = by.gsu.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
