/*
 * This file is generated by jOOQ.
 */
package by.gsu.jooq.tables.records;


import by.gsu.jooq.tables.Product;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record9<Integer, String, Float, Float, Float, Float, Float, Float, Float> {

    private static final long serialVersionUID = -2080278859;

    /**
     * Setter for <code>Product.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Product.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Product.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Product.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Product.vat</code>.
     */
    public void setVat(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>Product.vat</code>.
     */
    public Float getVat() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>Product.profit</code>.
     */
    public void setProfit(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>Product.profit</code>.
     */
    public Float getProfit() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>Product.salary</code>.
     */
    public void setSalary(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>Product.salary</code>.
     */
    public Float getSalary() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>Product.fuelAndEnergy</code>.
     */
    public void setFuelandenergy(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>Product.fuelAndEnergy</code>.
     */
    public Float getFuelandenergy() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>Product.recyclableWaste</code>.
     */
    public void setRecyclablewaste(Float value) {
        set(6, value);
    }

    /**
     * Getter for <code>Product.recyclableWaste</code>.
     */
    public Float getRecyclablewaste() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>Product.components</code>.
     */
    public void setComponents(Float value) {
        set(7, value);
    }

    /**
     * Getter for <code>Product.components</code>.
     */
    public Float getComponents() {
        return (Float) get(7);
    }

    /**
     * Setter for <code>Product.rawAndMaterials</code>.
     */
    public void setRawandmaterials(Float value) {
        set(8, value);
    }

    /**
     * Getter for <code>Product.rawAndMaterials</code>.
     */
    public Float getRawandmaterials() {
        return (Float) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Float, Float, Float, Float, Float, Float, Float> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Float, Float, Float, Float, Float, Float, Float> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return Product.PRODUCT.VAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field4() {
        return Product.PRODUCT.PROFIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return Product.PRODUCT.SALARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return Product.PRODUCT.FUELANDENERGY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field7() {
        return Product.PRODUCT.RECYCLABLEWASTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field8() {
        return Product.PRODUCT.COMPONENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field9() {
        return Product.PRODUCT.RAWANDMATERIALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component3() {
        return getVat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component4() {
        return getProfit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component5() {
        return getSalary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component6() {
        return getFuelandenergy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component7() {
        return getRecyclablewaste();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component8() {
        return getComponents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component9() {
        return getRawandmaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getVat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value4() {
        return getProfit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getSalary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getFuelandenergy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value7() {
        return getRecyclablewaste();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value8() {
        return getComponents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value9() {
        return getRawandmaterials();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(Float value) {
        setVat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(Float value) {
        setProfit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(Float value) {
        setSalary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Float value) {
        setFuelandenergy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(Float value) {
        setRecyclablewaste(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value8(Float value) {
        setComponents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value9(Float value) {
        setRawandmaterials(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Integer value1, String value2, Float value3, Float value4, Float value5, Float value6, Float value7, Float value8, Float value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, String name, Float vat, Float profit, Float salary, Float fuelandenergy, Float recyclablewaste, Float components, Float rawandmaterials) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, name);
        set(2, vat);
        set(3, profit);
        set(4, salary);
        set(5, fuelandenergy);
        set(6, recyclablewaste);
        set(7, components);
        set(8, rawandmaterials);
    }
}
