package by.gsu.form;

import by.gsu.model.Product;
import by.gsu.repository.impl.ProductRepositoryImpl;
import by.gsu.service.ProductService;
import by.gsu.service.ProductServiceImpl;
import org.jooq.tools.StringUtils;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.function.Supplier;
import java.util.stream.Stream;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

public class AddNewProduct extends AbstractForm {

    private static final String TITLE = "Добавление нового изделия";
    private static final int PREF_WIDTH = 400;
    private static final int PREF_HEIGHT = 400;

    private JPanel mainPanel;

    private JTextField textFieldName;
    private JTextField textFieldRecyclableAndWaste;
    private JTextField textFieldRawAndMaterials;
    private JTextField textFieldComponents;
    private JTextField textFieldFuelAndEnergy;
    private JTextField textFieldSalary;
    private JTextField textFieldVat;
    private JTextField textFieldProfit;

    private JButton buttonAdd;

    private ProductService productService;

    private MainForm mainForm;

    public AddNewProduct(MainForm mainForm) {
        $$$setupUI$$$();

        this.mainForm = mainForm;
        this.productService = new ProductServiceImpl(new ProductRepositoryImpl());

        Supplier<Stream<JTextField>> textFieldsStream = () -> Arrays.stream(mainPanel.getComponents())
                .filter(component -> component instanceof JTextField)
                .map(JTextField.class::cast);

        textFieldsStream.get().forEach(textField -> textField.setColumns(15));

        buttonAdd.addActionListener(e -> {
            long notFilledFieldsCount = textFieldsStream.get()
                    .filter(textField -> StringUtils.isEmpty(textField.getText()))
                    .count();

            if (notFilledFieldsCount > 0) {
                JOptionPane.showMessageDialog(mainPanel, "Заполните все поля!", "Ошибка", ERROR_MESSAGE);
                return;
            }

            try {
                productService.add(new Product.Builder()
                        .setName(textFieldName.getText())
                        .setRawAndMaterials(Float.valueOf(textFieldRawAndMaterials.getText()))
                        .setRecyclableAndWaste(Float.valueOf(textFieldRecyclableAndWaste.getText()))
                        .setComponents(Float.valueOf(textFieldComponents.getText()))
                        .setFuelAndEnergy(Float.valueOf(textFieldFuelAndEnergy.getText()))
                        .setSalary(Float.valueOf(textFieldSalary.getText()))
                        .setVat(Float.valueOf(textFieldVat.getText()))
                        .setProfit(Float.valueOf(textFieldProfit.getText()))
                        .build());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(mainPanel, "Числовые поля заполнены некорректно!", "Ошибка", ERROR_MESSAGE);
                return;
            }


            JOptionPane.showMessageDialog(mainPanel, "Запись успешно добавлена", "Информация", INFORMATION_MESSAGE);
            mainForm.initProductsTable();
        });
    }

    @Override
    public JPanel getMainPanel() {
        return mainPanel;
    }

    @Override
    public String getTitle() {
        return TITLE;
    }

    @Override
    public int getWidth() {
        return PREF_WIDTH;
    }

    @Override
    public int getHeight() {
        return PREF_HEIGHT;
    }

    @Override
    public int getDefaultCloseOperation() {
        return DO_NOTHING_ON_CLOSE;
    }

    @Override
    public void onCloseAction() {
        mainForm.initProductsTable();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        textFieldName = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 10);
        mainPanel.add(textFieldName, gbc);
        textFieldRawAndMaterials = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldRawAndMaterials, gbc);
        textFieldComponents = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldComponents, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Наименование изделия");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 10, 0, 10);
        mainPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Затраты на сырье и материалы, т. руб");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 10, 0, 10);
        mainPanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Затраты на комлектующие, т. руб ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 10, 0, 10);
        mainPanel.add(label3, gbc);
        buttonAdd = new JButton();
        buttonAdd.setText("Добавить");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 0, 10);
        mainPanel.add(buttonAdd, gbc);
        textFieldFuelAndEnergy = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldFuelAndEnergy, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Затраты на топливо и энергию, т. руб");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 10, 0, 10);
        mainPanel.add(label4, gbc);
        textFieldSalary = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldSalary, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Заработная плата сотрудникам, т. руб");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 0, 10);
        mainPanel.add(label5, gbc);
        textFieldRecyclableAndWaste = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldRecyclableAndWaste, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Возвратные отходы, %");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 10, 0, 10);
        mainPanel.add(label6, gbc);
        textFieldProfit = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldProfit, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Прибыль, %");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 10, 0, 10);
        mainPanel.add(label7, gbc);
        textFieldVat = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 0, 0, 10);
        mainPanel.add(textFieldVat, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("НДС, %");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 0, 10);
        mainPanel.add(label8, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
